version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: ./containers/nginx/Dockerfile
    ports:
      - "8089:80"
    depends_on:
      - cuba
  cuba:
    build:
      context: .
      dockerfile: ./containers/cuba/Dockerfile
